# Site settings
title: Shroud Walkers
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://shroudwalkers.pro" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shroud Walkers
user_description: The site is currently under construction. Please bear with us while we get everything in order!
user_title: A friendly FC based in Eorzea.
email: none@shroudwalkers.pro
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
